package enums;

public interface Constants {
	int GAMER_TEST = 0;
	int CITY_MAX_COLS = 20;
	int CITY_MAX_ROWS = 20;
	int DEGRADATION_CONSEVATION_FACTOR = 5;
	
	int HOUSE_CONSERVATION_COST_D = 50;
	int HOUSE_CONSERVATION_COST_C = 150;
	int HOUSE_CONSERVATION_COST_B = 300;
	int HOUSE_CONSERVATION_COST_BA = 800;
	int HOUSE_CONSERVATION_COST_A = 3000;
	int HOUSE_CONSERVATION_COST_AA = 4000;
}
